**Name:Mohammad Abubakr Khanooni**


**Roll no :A2-27**

**DA Practical 1:**

**Aim:Write a program read the file and find Minimum and Maximum using Brute force approach. Also propose and implement an improved algorithm based on Divide and Conquer Strategy. Also calculate the time taken by both the algotihm. **


In [19]:
import pandas as pd
import numpy as np
bruteforce=np.array([0,0,0,0,0])#will store the time taken by 5 of the csv files in each index by bruteforce
dandc=np.array([0,0,0,0,0])#will store the time taken by 5 of the csv files in each index by D&C algo

In [20]:
df = pd.read_csv('data500.csv')
second_column_values = df.iloc[:, 0].values
print(second_column_values)

[255  78 768 187 481  53 948 760 820 532 205 998 406  12 456 624 335 135
 589 623 332 327 394 106 932 899 406 895 523 612 259 786 561  80 575 935
 249 680 117 825  65 325 865 931 353 541 289 405 210 721 474 706 992 931
  15 797  18 936 662 840 192 719 122 936 517 228 576 675 961 814 681 134
 412 638 690 523 963 994 926 824 638 495 680   9 317 500 850 994 454  99
 334 850 249 780 635 244 318 848 352 889 791 840 570 473 220 172 338 447
 392 958 905 572 365 410 736 624 392 690 112 907  90 687 650   4 133 804
  87 501 247 600 208 198 230 338 793 527 220 459 769  27 498 322 951  69
 715 274 610 900 971 254 355 249 757 963 611 177 713 300 885  59 176 231
 617 243 236 635 788 880 347 600 606 125 480 583 278 722  86 469 971 921
 371 541 453 542 173 321 773 751  80 625 225 939 644 848 274 745 112  85
 830 841  94 343 277  70 682 409 281 333 443 775 142 222 772  38 783  70
 571 570 840 517 196 822 731 627 410 707 676 645  75 514  87 640 670 470
 391 608 153 402 695 363 426 845 337 380 550 520 57

In [21]:
hello=type(second_column_values)
print(hello)

<class 'numpy.ndarray'>


In [22]:
import numpy as np

In [23]:
arr=np.array(second_column_values)
print(arr)
a=len(arr)
print(a)

[255  78 768 187 481  53 948 760 820 532 205 998 406  12 456 624 335 135
 589 623 332 327 394 106 932 899 406 895 523 612 259 786 561  80 575 935
 249 680 117 825  65 325 865 931 353 541 289 405 210 721 474 706 992 931
  15 797  18 936 662 840 192 719 122 936 517 228 576 675 961 814 681 134
 412 638 690 523 963 994 926 824 638 495 680   9 317 500 850 994 454  99
 334 850 249 780 635 244 318 848 352 889 791 840 570 473 220 172 338 447
 392 958 905 572 365 410 736 624 392 690 112 907  90 687 650   4 133 804
  87 501 247 600 208 198 230 338 793 527 220 459 769  27 498 322 951  69
 715 274 610 900 971 254 355 249 757 963 611 177 713 300 885  59 176 231
 617 243 236 635 788 880 347 600 606 125 480 583 278 722  86 469 971 921
 371 541 453 542 173 321 773 751  80 625 225 939 644 848 274 745 112  85
 830 841  94 343 277  70 682 409 281 333 443 775 142 222 772  38 783  70
 571 570 840 517 196 822 731 627 410 707 676 645  75 514  87 640 670 470
 391 608 153 402 695 363 426 845 337 380 550 520 57

**brute force method**

In [24]:
def findMinMax(X, n):
    max_val = X[0]
    min_val = X[0]

    for i in range(1, n):
        if X[i] > max_val:
            max_val = X[i]
        elif X[i] < min_val:
            min_val = X[i]

    max_min = [max_val, min_val]
    return max_min


In [25]:
arr1=findMinMax(arr,a)

In [26]:
print("the maximum element is",arr1[0]," and minimum element is ",arr1[1])

the maximum element is 998  and minimum element is  4


In [42]:
print("the time complexity of brute force algorithm is ")
import time
start=time.perf_counter()
findMinMax(arr,500)
end= time.perf_counter()
timetaken=end-start
print(timetaken)
bruteforce[0]=timetaken

the time complexity of brute force algorithm is 
0.0003694299999779105


**divide and conquer**

In [28]:
def findMinMaxnew(X, l, r):#using divide and conquer
    max, min = 0, 0
    if l == r:#when the array got split into an array containing only one element
        max = X[l]
        min = X[l]
    elif l + 1 == r:#when its having two elements
        if X[l] < X[r]:
            max = X[r]
            min = X[l]
        else:
            max = X[l]
            min = X[r]
    else:
        mid = l + (r - l) // 2
        leftMinMax = findMinMaxnew(X, l, mid)#calling recursively until either of the above two conditions meet
        rightMinMax = findMinMaxnew(X, mid + 1, r)
        if leftMinMax[0] > rightMinMax[0]:
            max = leftMinMax[0]
        else:
            max = rightMinMax[0]
        if leftMinMax[1] < rightMinMax[1]:
            min = leftMinMax[1]
        else:
            min = rightMinMax[1]
    maxMin = [max, min]
    return maxMin

In [29]:
arr2=findMinMaxnew(arr,0,a-1)

In [30]:
print("the maximum element is",arr2[0]," and minimum element is ",arr2[1])

the maximum element is 998  and minimum element is  4


In [43]:
print("the time complexity of divide and conquer algorithm is ")
import time
start=time.perf_counter()
findMinMaxnew(arr,0,a-1)
end= time.perf_counter()
timetaken=end-start
print(timetaken)
dandc[0]=timetaken

the time complexity of divide and conquer algorithm is 
0.0001669040000251698








For next csv file-test1.csv



In [32]:
df1 = pd.read_csv('test1.csv')
second_column_values1 = df1.iloc[:, 1].values
print(second_column_values1)

[35.2  36.65 37.13 37.1  38.03 38.91 38.51 38.22 39.64 40.15 40.37 40.4
 40.58 40.5  38.4  38.72 37.01 36.2  37.13 34.54 36.16 38.65 37.84]


In [33]:
arr_2nd=np.array(second_column_values1)
print(arr_2nd)
a=len(arr_2nd)
print(a)

[35.2  36.65 37.13 37.1  38.03 38.91 38.51 38.22 39.64 40.15 40.37 40.4
 40.58 40.5  38.4  38.72 37.01 36.2  37.13 34.54 36.16 38.65 37.84]
23


In [38]:
#bruteforce
arr10=findMinMax(arr_2nd,a)
print("the maximum element is",arr10[0]," and minimum element is ",arr10[1])

the maximum element is 40.58  and minimum element is  34.54


In [44]:
print("the time complexity of brute force algorithm is ")
import time
start=time.perf_counter()
findMinMax(arr_2nd,len(arr_2nd))
end= time.perf_counter()
timetaken=end-start
print(timetaken)


the time complexity of brute force algorithm is 
0.0001653870000382085


In [45]:
bruteforce[1]=timetaken

In [40]:
#for d and c
arr2=findMinMaxnew(arr_2nd,0,len(arr_2nd)-1)
print("the maximum element is",arr2[0]," and minimum element is ",arr2[1])


the maximum element is 40.58  and minimum element is  34.54


In [46]:
print("the time complexity of divide and conquer algorithm is ")
import time
start=time.perf_counter()
arr2=findMinMaxnew(arr_2nd,0,len(arr_2nd)-1)
end= time.perf_counter()
timetaken=end-start
print(timetaken)

the time complexity of divide and conquer algorithm is 
0.00021900999996660175


In [47]:
dandc[1]=timetaken

for next csv file-test2.csv

In [50]:
df = pd.read_csv('test2.csv')
second_column_values = df.iloc[:, 1].values
print(second_column_values)

[ 4.5 16.9  5.7 ... 14.   9.7 12.9]


In [51]:
arr=np.array(second_column_values)
print(arr)
a=len(arr)
print(a)

[ 4.5 16.9  5.7 ... 14.   9.7 12.9]
78416


In [52]:
#using bruteforce
arr1=findMinMax(arr,a)
print("the maximum element is",arr1[0]," and minimum element is ",arr1[1])
print("the time complexity of brute force algorithm is ")
import time
start=time.perf_counter()
findMinMax(arr,500)
end= time.perf_counter()
timetaken=end-start
print(timetaken)
bruteforce[2]=timetaken


the maximum element is 200.0  and minimum element is  -44.9
the time complexity of brute force algorithm is 
0.00022133799996026937


In [53]:
#using divide and conquer
arr2=findMinMaxnew(arr,0,a-1)
print("the maximum element is",arr2[0]," and minimum element is ",arr2[1])
print("the time complexity of divide and conquer algorithm is ")
import time
start=time.perf_counter()
findMinMaxnew(arr,0,a-1)
end= time.perf_counter()
timetaken=end-start
print(timetaken)
dandc[2]=timetaken

the maximum element is 200.0  and minimum element is  -44.9
the time complexity of divide and conquer algorithm is 
0.057893478000096366


for fourth csv file=test3.csv

In [57]:
df = pd.read_csv('test3.csv')
second_column_values = df.iloc[:, 1].values
print(second_column_values)

[15.07 14.89 14.45 ... 76.64 72.74 72.7 ]


In [58]:
arr=np.array(second_column_values)
print(arr)
a=len(arr)
print(a)

[15.07 14.89 14.45 ... 76.64 72.74 72.7 ]
619040


In [59]:
#using bruteforce
arr1=findMinMax(arr,a)
print("the maximum element is",arr1[0]," and minimum element is ",arr1[1])
print("the time complexity of brute force algorithm is ")
import time
start=time.perf_counter()
findMinMax(arr,500)
end= time.perf_counter()
timetaken=end-start
print(timetaken)
bruteforce[3]=timetaken

the maximum element is 2044.0  and minimum element is  1.62
the time complexity of brute force algorithm is 
0.00020742099991366558


In [60]:
#using divide and conquer
arr2=findMinMaxnew(arr,0,a-1)
print("the maximum element is",arr2[0]," and minimum element is ",arr2[1])
print("the time complexity of divide and conquer algorithm is ")
import time
start=time.perf_counter()
findMinMaxnew(arr,0,a-1)
end= time.perf_counter()
timetaken=end-start
print(timetaken)
dandc[3]=timetaken

the maximum element is 2044.0  and minimum element is  1.62
the time complexity of divide and conquer algorithm is 
0.44398223300004247


for fifth csv file-test4.csv

In [64]:
df = pd.read_csv('test4.csv')
second_column_values = df.iloc[:, 10].values
print(second_column_values)

[1.2600000e-01 1.2600000e-01 1.2600000e-01 ... 1.5736835e+04 1.5818731e+04
 1.5837284e+04]


In [65]:
arr=np.array(second_column_values)
print(arr)
a=len(arr)
print(a)

[1.2600000e-01 1.2600000e-01 1.2600000e-01 ... 1.5736835e+04 1.5818731e+04
 1.5837284e+04]
166326


In [66]:
#using bruteforce
arr1=findMinMax(arr,a)
print("the maximum element is",arr1[0]," and minimum element is ",arr1[1])
print("the time complexity of brute force algorithm is ")
import time
start=time.perf_counter()
findMinMax(arr,500)
end= time.perf_counter()
timetaken=end-start
print(timetaken)
bruteforce[4]=timetaken

the maximum element is 706541.904  and minimum element is  0.001
the time complexity of brute force algorithm is 
0.00019895499963240582


In [67]:
#using divide and conquer
arr2=findMinMaxnew(arr,0,a-1)
print("the maximum element is",arr2[0]," and minimum element is ",arr2[1])
print("the time complexity of divide and conquer algorithm is ")
import time
start=time.perf_counter()
findMinMaxnew(arr,0,a-1)
end= time.perf_counter()
timetaken=end-start
print(timetaken)
dandc[4]=timetaken

the maximum element is 706541.904  and minimum element is  0.001
the time complexity of divide and conquer algorithm is 
0.12416197900029147


In [73]:

print(bruteforce+1)
print(dandc+1)

[1 1 1 1 1]
[1 1 1 1 1]


In [ ]:
#since the values are so small python is notdisplaying such short values